### ISSUE TITLE
Crash of initcontainer due to panic

### ISSUE THREAD

**Issue by zefciu** [Mirantis/k8s-AppController#85]
When running appcontroller initcontainer I get:

```
panic: interface conversion: error is *url.Error, not *errors.StatusError

goroutine 1 [running]:
panic(0x1819800, 0xc4203f8080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Mirantis/k8s-AppController/cmd.createTPRIfNotExists(0xc42030d140, 0x12, 0xc42030d120, 0x12, 0xc42030d100, 0x1d, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/Mirantis/k8s-AppController/cmd/bootstrap.go:43 +0x1d7
github.com/Mirantis/k8s-AppController/cmd.bootstrap(0x23d8300, 0xc420432200, 0x1, 0x1)
        /go/src/github.com/Mirantis/k8s-AppController/cmd/bootstrap.go:83 +0x252
github.com/spf13/cobra.(*Command).execute(0x23d8300, 0xc4204321c0, 0x1, 0x1, 0x23d8300, 0xc4204321c0)
        /go/src/github.com/spf13/cobra/command.go:603 +0x439
github.com/spf13/cobra.(*Command).ExecuteC(0xc4203de6c0, 0x0, 0x0, 0x0)
        /go/src/github.com/spf13/cobra/command.go:689 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc4203de6c0, 0x0, 0x0)
        /go/src/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /go/src/github.com/Mirantis/k8s-AppController/main.go:26 +0x36
```

**Comment by zefciu** [comment]
I see the reason of panic, I will correct this and find the underlying error.

**Comment by nebril** [comment]
Fixed by #86

**Comment by zefciu** [comment]
The error that caused the panic happens (for unknown reasons yet) when using local-up-cluster. There are no reported problems with minikube.

**Comment by pigmej** [comment]
@zefciu but is the panic fixed?

**Comment by zefciu** [comment]
The panic is fixed. Now in this case you get correctly logged that it couldn't dial the kubernetes service. This is not a fault of appcontroller. I just mentioned it here for information.
